package com.hihihigh.crm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.hihihigh.crm.model.autogenerator.CustomerDevelopment;
import com.hihihigh.crm.model.autogenerator.CustomerDevelopmentExample;

public interface CustomerDevelopmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int countByExample(CustomerDevelopmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerDevelopmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int insert(CustomerDevelopment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int insertSelective(CustomerDevelopment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    List<CustomerDevelopment> selectByExample(CustomerDevelopmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    CustomerDevelopment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerDevelopment record, @Param("example") CustomerDevelopmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerDevelopment record, @Param("example") CustomerDevelopmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerDevelopment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerDevelopment record);
}