package com.hihihigh.crm.dao;

import com.hihihigh.crm.model.autogenerator.CustomerDevelopmentBefore;
import com.hihihigh.crm.model.autogenerator.CustomerDevelopmentBeforeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerDevelopmentBeforeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int countByExample(CustomerDevelopmentBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerDevelopmentBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int insert(CustomerDevelopmentBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int insertSelective(CustomerDevelopmentBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    List<CustomerDevelopmentBefore> selectByExample(CustomerDevelopmentBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    CustomerDevelopmentBefore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerDevelopmentBefore record, @Param("example") CustomerDevelopmentBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerDevelopmentBefore record, @Param("example") CustomerDevelopmentBeforeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerDevelopmentBefore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development_before
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerDevelopmentBefore record);
}