package com.hihihigh.crm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.hihihigh.crm.model.autogenerator.StatusCustmer;
import com.hihihigh.crm.model.autogenerator.StatusCustmerExample;

public interface StatusCustmerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int countByExample(StatusCustmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int deleteByExample(StatusCustmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int insert(StatusCustmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int insertSelective(StatusCustmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    List<StatusCustmer> selectByExample(StatusCustmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    StatusCustmer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StatusCustmer record, @Param("example") StatusCustmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StatusCustmer record, @Param("example") StatusCustmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatusCustmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_custmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatusCustmer record);
}