package com.hihihigh.crm.model.autogenerator;

import java.util.ArrayList;

import com.hihihigh.crm.tool.Excelable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Account implements Excelable{
    /**
     * Database Column Remarks:
     *   账号表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   员工昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   员工表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_employee_id
     *
     * @mbggenerated
     */
    private Integer accountEmployeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.nick_name
     *
     * @return the value of account.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.nick_name
     *
     * @param nickName the value for account.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_employee_id
     *
     * @return the value of account.account_employee_id
     *
     * @mbggenerated
     */
    public Integer getAccountEmployeeId() {
        return accountEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_employee_id
     *
     * @param accountEmployeeId the value for account.account_employee_id
     *
     * @mbggenerated
     */
    public void setAccountEmployeeId(Integer accountEmployeeId) {
        this.accountEmployeeId = accountEmployeeId;
    }

	public Account(String username, String password, String nickName, Integer accountEmployeeId) {
		super();
		this.username = username;
		this.password = password;
		this.nickName = nickName;
		this.accountEmployeeId = accountEmployeeId;
	}

	public Account() {
		super();
	}

	@Override
	public String toString() {
		return "Account [id=" + id + ", username=" + username + ", password=" + password + ", nickName=" + nickName
				+ ", accountEmployeeId=" + accountEmployeeId + "]";
	}

	public Account(String username, String password, String nickName) {
		super();
		this.username = username;
		this.password = password;
		this.nickName = nickName;
	}

	@Override
	public ArrayList<String> getAllFieldValuesByString() {
		ArrayList<String> fieldValues = new ArrayList<>();
		fieldValues.add(id.toString());
		fieldValues.add(username);
		fieldValues.add(password);
		fieldValues.add(nickName);
		fieldValues.add(accountEmployeeId.toString());
		return fieldValues;
	}

	public static ArrayList<String> getAllFields() {
		ArrayList<String> fields = new ArrayList<>();
		fields.add("id");
		fields.add("username");
		fields.add("password");
		fields.add("nickName");
		fields.add("accountEmployeeId");
		return fields;
	}
}