package com.hihihigh.crm.model.autogenerator;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table authority
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Authority {
    /**
     * Database Column Remarks:
     *   权限表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   职务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_position_id
     *
     * @mbggenerated
     */
    private Integer authorityPositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_name_authority_id
     *
     * @mbggenerated
     */
    private Integer authorityNameAuthorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_position_id
     *
     * @return the value of authority.authority_position_id
     *
     * @mbggenerated
     */
    public Integer getAuthorityPositionId() {
        return authorityPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_position_id
     *
     * @param authorityPositionId the value for authority.authority_position_id
     *
     * @mbggenerated
     */
    public void setAuthorityPositionId(Integer authorityPositionId) {
        this.authorityPositionId = authorityPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_name_authority_id
     *
     * @return the value of authority.authority_name_authority_id
     *
     * @mbggenerated
     */
    public Integer getAuthorityNameAuthorityId() {
        return authorityNameAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_name_authority_id
     *
     * @param authorityNameAuthorityId the value for authority.authority_name_authority_id
     *
     * @mbggenerated
     */
    public void setAuthorityNameAuthorityId(Integer authorityNameAuthorityId) {
        this.authorityNameAuthorityId = authorityNameAuthorityId;
    }

	public Authority() {
		super();
	}

	public Authority(Integer authorityPositionId, Integer authorityNameAuthorityId) {
		super();
		this.authorityPositionId = authorityPositionId;
		this.authorityNameAuthorityId = authorityNameAuthorityId;
	}
}