package com.hihihigh.crm.model.autogenerator;

import java.util.ArrayList;
import java.util.Date;

import com.hihihigh.crm.tool.Excelable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Customer implements Excelable{
    /**
     * Database Column Remarks:
     *   客户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated
     */
    private Integer id;

	/**
     * Database Column Remarks:
     *   客户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   教育水平
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.educational_level
     *
     * @mbggenerated
     */
    private String educationalLevel;

    /**
     * Database Column Remarks:
     *   客户手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_telephone
     *
     * @mbggenerated
     */
    private String customerTelephone;

    /**
     * Database Column Remarks:
     *   qq
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.qq
     *
     * @mbggenerated
     */
    private Integer qq;

    /**
     * Database Column Remarks:
     *   客户邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_email
     *
     * @mbggenerated
     */
    private String customerEmail;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custmer_status_customer_id
     *
     * @mbggenerated
     */
    private Integer custmerStatusCustomerId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   咨询备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_remark
     *
     * @mbggenerated
     */
    private String customerRemark;

    public Customer(int customerId, int custmerStatusCustomerId, String customerRemark) {
		id = customerId;
		this.custmerStatusCustomerId = custmerStatusCustomerId;
		this.customerRemark = customerRemark;
	}

	public Customer() {
		super();
	}

	public Customer(String customerName, String educationalLevel,
			String customerTelephone, Integer qq, String customerEmail,
			Integer custmerStatusCustomerId, String customerRemark) {
		this.customerName = customerName;
		this.educationalLevel = educationalLevel;
		this.customerTelephone = customerTelephone;
		this.qq = qq;
		this.customerEmail = customerEmail;
		this.custmerStatusCustomerId = custmerStatusCustomerId;
		this.customerRemark = customerRemark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.educational_level
     *
     * @return the value of customer.educational_level
     *
     * @mbggenerated
     */
    public String getEducationalLevel() {
        return educationalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.educational_level
     *
     * @param educationalLevel the value for customer.educational_level
     *
     * @mbggenerated
     */
    public void setEducationalLevel(String educationalLevel) {
        this.educationalLevel = educationalLevel == null ? null : educationalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_telephone
     *
     * @return the value of customer.customer_telephone
     *
     * @mbggenerated
     */
    public String getCustomerTelephone() {
        return customerTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_telephone
     *
     * @param customerTelephone the value for customer.customer_telephone
     *
     * @mbggenerated
     */
    public void setCustomerTelephone(String customerTelephone) {
        this.customerTelephone = customerTelephone == null ? null : customerTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.qq
     *
     * @return the value of customer.qq
     *
     * @mbggenerated
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.qq
     *
     * @param qq the value for customer.qq
     *
     * @mbggenerated
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_email
     *
     * @return the value of customer.customer_email
     *
     * @mbggenerated
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_email
     *
     * @param customerEmail the value for customer.customer_email
     *
     * @mbggenerated
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custmer_status_customer_id
     *
     * @return the value of customer.custmer_status_customer_id
     *
     * @mbggenerated
     */
    public Integer getCustmerStatusCustomerId() {
        return custmerStatusCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custmer_status_customer_id
     *
     * @param custmerStatusCustomerId the value for customer.custmer_status_customer_id
     *
     * @mbggenerated
     */
    public void setCustmerStatusCustomerId(Integer custmerStatusCustomerId) {
        this.custmerStatusCustomerId = custmerStatusCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_time
     *
     * @return the value of customer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_time
     *
     * @param createTime the value for customer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_remark
     *
     * @return the value of customer.customer_remark
     *
     * @mbggenerated
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_remark
     *
     * @param customerRemark the value for customer.customer_remark
     *
     * @mbggenerated
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark == null ? null : customerRemark.trim();
    }
    

    @Override
	public String toString() {
		return "Customer [id=" + id + ", customerName=" + customerName + ", educationalLevel=" + educationalLevel
				+ ", customerTelephone=" + customerTelephone + ", qq=" + qq + ", customerEmail=" + customerEmail
				+ ", custmerStatusCustomerId=" + custmerStatusCustomerId + ", createTime=" + createTime
				+ ", customerRemark=" + customerRemark + "]";
	}

	public static ArrayList<String> getAllFields() {
		ArrayList<String> fields = new ArrayList<>();
		fields.add("编号id");
		fields.add("客户名");
		fields.add("学历");
		fields.add("电话号");
		fields.add("qq");
		fields.add("邮箱");
		fields.add("状态");
		fields.add("创建时间");
		fields.add("备注");
		return fields;
	}

	@Override
	public ArrayList<String> getAllFieldValuesByString() {
		ArrayList<String> fieldValues = new ArrayList<>();
		fieldValues.add(id.toString());
		fieldValues.add(customerName);
		fieldValues.add(educationalLevel==null?"":educationalLevel);
		fieldValues.add(customerTelephone);
		fieldValues.add(qq==null?"":qq.toString());
		fieldValues.add(customerEmail==null?"":customerEmail);
		fieldValues.add(custmerStatusCustomerId.toString());
		fieldValues.add(createTime.toString());
		fieldValues.add(customerRemark==null?"":customerRemark);
		return fieldValues;
	}
}