package com.hihihigh.crm.model.autogenerator;

import java.util.ArrayList;
import java.util.Date;

import com.hihihigh.crm.tool.Excelable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_development_before
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CustomerDevelopmentBefore implements Excelable{
    public CustomerDevelopmentBefore() {
		super();
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.cd0_customer_id
     *
     * @mbggenerated
     */
    private Integer cd0CustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.cd0_allocation_time
     *
     * @mbggenerated
     */
    private Date cd0AllocationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.next_contact_time
     *
     * @mbggenerated
     */
    private Date nextContactTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.last_contact_time
     *
     * @mbggenerated
     */
    private Date lastContactTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.cd0_employee_id
     *
     * @mbggenerated
     */
    private Integer cd0EmployeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.valid_cellphone
     *
     * @mbggenerated
     */
    private Integer validCellphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_development_before.picked_phone
     *
     * @mbggenerated
     */
    private Integer pickedPhone;

    public CustomerDevelopmentBefore(int id, Date date) {
    	this.id = id;
    	this.nextContactTime = date;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.id
     *
     * @return the value of customer_development_before.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.id
     *
     * @param id the value for customer_development_before.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.cd0_customer_id
     *
     * @return the value of customer_development_before.cd0_customer_id
     *
     * @mbggenerated
     */
    public Integer getCd0CustomerId() {
        return cd0CustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.cd0_customer_id
     *
     * @param cd0CustomerId the value for customer_development_before.cd0_customer_id
     *
     * @mbggenerated
     */
    public void setCd0CustomerId(Integer cd0CustomerId) {
        this.cd0CustomerId = cd0CustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.cd0_allocation_time
     *
     * @return the value of customer_development_before.cd0_allocation_time
     *
     * @mbggenerated
     */
    public Date getCd0AllocationTime() {
        return cd0AllocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.cd0_allocation_time
     *
     * @param cd0AllocationTime the value for customer_development_before.cd0_allocation_time
     *
     * @mbggenerated
     */
    public void setCd0AllocationTime(Date cd0AllocationTime) {
        this.cd0AllocationTime = cd0AllocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.next_contact_time
     *
     * @return the value of customer_development_before.next_contact_time
     *
     * @mbggenerated
     */
    public Date getNextContactTime() {
        return nextContactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.next_contact_time
     *
     * @param nextContactTime the value for customer_development_before.next_contact_time
     *
     * @mbggenerated
     */
    public void setNextContactTime(Date nextContactTime) {
        this.nextContactTime = nextContactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.last_contact_time
     *
     * @return the value of customer_development_before.last_contact_time
     *
     * @mbggenerated
     */
    public Date getLastContactTime() {
        return lastContactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.last_contact_time
     *
     * @param lastContactTime the value for customer_development_before.last_contact_time
     *
     * @mbggenerated
     */
    public void setLastContactTime(Date lastContactTime) {
        this.lastContactTime = lastContactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.cd0_employee_id
     *
     * @return the value of customer_development_before.cd0_employee_id
     *
     * @mbggenerated
     */
    public Integer getCd0EmployeeId() {
        return cd0EmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.cd0_employee_id
     *
     * @param cd0EmployeeId the value for customer_development_before.cd0_employee_id
     *
     * @mbggenerated
     */
    public void setCd0EmployeeId(Integer cd0EmployeeId) {
        this.cd0EmployeeId = cd0EmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.valid_cellphone
     *
     * @return the value of customer_development_before.valid_cellphone
     *
     * @mbggenerated
     */
    public Integer getValidCellphone() {
        return validCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.valid_cellphone
     *
     * @param validCellphone the value for customer_development_before.valid_cellphone
     *
     * @mbggenerated
     */
    public void setValidCellphone(Integer validCellphone) {
        this.validCellphone = validCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_development_before.picked_phone
     *
     * @return the value of customer_development_before.picked_phone
     *
     * @mbggenerated
     */
    public Integer getPickedPhone() {
        return pickedPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_development_before.picked_phone
     *
     * @param pickedPhone the value for customer_development_before.picked_phone
     *
     * @mbggenerated
     */
    public void setPickedPhone(Integer pickedPhone) {
        this.pickedPhone = pickedPhone;
    }

    
    @Override
	public String toString() {
		return "CustomerDevelopmentBefore [id=" + id + ", cd0CustomerId=" + cd0CustomerId + ", cd0AllocationTime="
				+ cd0AllocationTime + ", nextContactTime=" + nextContactTime + ", lastContactTime=" + lastContactTime
				+ ", cd0EmployeeId=" + cd0EmployeeId + ", validCellphone=" + validCellphone + ", pickedPhone="
				+ pickedPhone + "]";
	}

	@Override
	public ArrayList<String> getAllFieldValuesByString() {
		ArrayList<String> fieldValues = new ArrayList<>();
		fieldValues.add(id.toString());
		fieldValues.add(cd0CustomerId.toString());
		fieldValues.add(cd0AllocationTime.toString());
		fieldValues.add(nextContactTime==null?"":nextContactTime.toString());
		fieldValues.add(lastContactTime==null?"":lastContactTime.toString());
		fieldValues.add(cd0EmployeeId.toString());
		fieldValues.add(validCellphone==null?"":validCellphone.toString());
		fieldValues.add(pickedPhone==null?"":pickedPhone.toString());
		return fieldValues;
	}

	public static ArrayList<String> getAllFields() {
		ArrayList<String> fields = new ArrayList<>();
		fields.add("编号id");
		fields.add("客户id");
		fields.add("分配时间");
		fields.add("下次见面时间");
		fields.add("上次见面时间");
		fields.add("负责员工id");
		fields.add("电话号是否可用");
		fields.add("接通次数");
		return fields;
	}
}