package com.hihihigh.crm.model.autogenerator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerDevelopmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public CustomerDevelopmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdIsNull() {
            addCriterion("cd_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdIsNotNull() {
            addCriterion("cd_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdEqualTo(Integer value) {
            addCriterion("cd_customer_id =", value, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdNotEqualTo(Integer value) {
            addCriterion("cd_customer_id <>", value, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdGreaterThan(Integer value) {
            addCriterion("cd_customer_id >", value, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cd_customer_id >=", value, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdLessThan(Integer value) {
            addCriterion("cd_customer_id <", value, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("cd_customer_id <=", value, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdIn(List<Integer> values) {
            addCriterion("cd_customer_id in", values, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdNotIn(List<Integer> values) {
            addCriterion("cd_customer_id not in", values, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("cd_customer_id between", value1, value2, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andCdCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cd_customer_id not between", value1, value2, "cdCustomerId");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeIsNull() {
            addCriterion("allocation_time is null");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeIsNotNull() {
            addCriterion("allocation_time is not null");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeEqualTo(Date value) {
            addCriterion("allocation_time =", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeNotEqualTo(Date value) {
            addCriterion("allocation_time <>", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeGreaterThan(Date value) {
            addCriterion("allocation_time >", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("allocation_time >=", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeLessThan(Date value) {
            addCriterion("allocation_time <", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeLessThanOrEqualTo(Date value) {
            addCriterion("allocation_time <=", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeIn(List<Date> values) {
            addCriterion("allocation_time in", values, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeNotIn(List<Date> values) {
            addCriterion("allocation_time not in", values, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeBetween(Date value1, Date value2) {
            addCriterion("allocation_time between", value1, value2, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeNotBetween(Date value1, Date value2) {
            addCriterion("allocation_time not between", value1, value2, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeIsNull() {
            addCriterion("next_contact_time is null");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeIsNotNull() {
            addCriterion("next_contact_time is not null");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeEqualTo(Date value) {
            addCriterion("next_contact_time =", value, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeNotEqualTo(Date value) {
            addCriterion("next_contact_time <>", value, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeGreaterThan(Date value) {
            addCriterion("next_contact_time >", value, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("next_contact_time >=", value, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeLessThan(Date value) {
            addCriterion("next_contact_time <", value, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeLessThanOrEqualTo(Date value) {
            addCriterion("next_contact_time <=", value, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeIn(List<Date> values) {
            addCriterion("next_contact_time in", values, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeNotIn(List<Date> values) {
            addCriterion("next_contact_time not in", values, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeBetween(Date value1, Date value2) {
            addCriterion("next_contact_time between", value1, value2, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andNextContactTimeNotBetween(Date value1, Date value2) {
            addCriterion("next_contact_time not between", value1, value2, "nextContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeIsNull() {
            addCriterion("last_contact_time is null");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeIsNotNull() {
            addCriterion("last_contact_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeEqualTo(Date value) {
            addCriterion("last_contact_time =", value, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeNotEqualTo(Date value) {
            addCriterion("last_contact_time <>", value, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeGreaterThan(Date value) {
            addCriterion("last_contact_time >", value, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_contact_time >=", value, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeLessThan(Date value) {
            addCriterion("last_contact_time <", value, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_contact_time <=", value, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeIn(List<Date> values) {
            addCriterion("last_contact_time in", values, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeNotIn(List<Date> values) {
            addCriterion("last_contact_time not in", values, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeBetween(Date value1, Date value2) {
            addCriterion("last_contact_time between", value1, value2, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andLastContactTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_contact_time not between", value1, value2, "lastContactTime");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdIsNull() {
            addCriterion("cd_employee_id is null");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdIsNotNull() {
            addCriterion("cd_employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdEqualTo(Integer value) {
            addCriterion("cd_employee_id =", value, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdNotEqualTo(Integer value) {
            addCriterion("cd_employee_id <>", value, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdGreaterThan(Integer value) {
            addCriterion("cd_employee_id >", value, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cd_employee_id >=", value, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdLessThan(Integer value) {
            addCriterion("cd_employee_id <", value, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdLessThanOrEqualTo(Integer value) {
            addCriterion("cd_employee_id <=", value, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdIn(List<Integer> values) {
            addCriterion("cd_employee_id in", values, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdNotIn(List<Integer> values) {
            addCriterion("cd_employee_id not in", values, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdBetween(Integer value1, Integer value2) {
            addCriterion("cd_employee_id between", value1, value2, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andCdEmployeeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cd_employee_id not between", value1, value2, "cdEmployeeId");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneIsNull() {
            addCriterion("valid_cellphone is null");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneIsNotNull() {
            addCriterion("valid_cellphone is not null");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneEqualTo(Integer value) {
            addCriterion("valid_cellphone =", value, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneNotEqualTo(Integer value) {
            addCriterion("valid_cellphone <>", value, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneGreaterThan(Integer value) {
            addCriterion("valid_cellphone >", value, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("valid_cellphone >=", value, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneLessThan(Integer value) {
            addCriterion("valid_cellphone <", value, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneLessThanOrEqualTo(Integer value) {
            addCriterion("valid_cellphone <=", value, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneIn(List<Integer> values) {
            addCriterion("valid_cellphone in", values, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneNotIn(List<Integer> values) {
            addCriterion("valid_cellphone not in", values, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneBetween(Integer value1, Integer value2) {
            addCriterion("valid_cellphone between", value1, value2, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andValidCellphoneNotBetween(Integer value1, Integer value2) {
            addCriterion("valid_cellphone not between", value1, value2, "validCellphone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneIsNull() {
            addCriterion("picked_phone is null");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneIsNotNull() {
            addCriterion("picked_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneEqualTo(Integer value) {
            addCriterion("picked_phone =", value, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneNotEqualTo(Integer value) {
            addCriterion("picked_phone <>", value, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneGreaterThan(Integer value) {
            addCriterion("picked_phone >", value, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("picked_phone >=", value, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneLessThan(Integer value) {
            addCriterion("picked_phone <", value, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("picked_phone <=", value, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneIn(List<Integer> values) {
            addCriterion("picked_phone in", values, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneNotIn(List<Integer> values) {
            addCriterion("picked_phone not in", values, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneBetween(Integer value1, Integer value2) {
            addCriterion("picked_phone between", value1, value2, "pickedPhone");
            return (Criteria) this;
        }

        public Criteria andPickedPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("picked_phone not between", value1, value2, "pickedPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_development
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_development
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}