package com.hihihigh.crm.model.autogenerator;

import java.util.ArrayList;
import java.util.List;

public class EmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public EmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNull() {
            addCriterion("employee_name is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNotNull() {
            addCriterion("employee_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameEqualTo(String value) {
            addCriterion("employee_name =", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotEqualTo(String value) {
            addCriterion("employee_name <>", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThan(String value) {
            addCriterion("employee_name >", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("employee_name >=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThan(String value) {
            addCriterion("employee_name <", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThanOrEqualTo(String value) {
            addCriterion("employee_name <=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLike(String value) {
            addCriterion("employee_name like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotLike(String value) {
            addCriterion("employee_name not like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIn(List<String> values) {
            addCriterion("employee_name in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotIn(List<String> values) {
            addCriterion("employee_name not in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameBetween(String value1, String value2) {
            addCriterion("employee_name between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotBetween(String value1, String value2) {
            addCriterion("employee_name not between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameIsNull() {
            addCriterion("employee_position_name is null");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameIsNotNull() {
            addCriterion("employee_position_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameEqualTo(String value) {
            addCriterion("employee_position_name =", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameNotEqualTo(String value) {
            addCriterion("employee_position_name <>", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameGreaterThan(String value) {
            addCriterion("employee_position_name >", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameGreaterThanOrEqualTo(String value) {
            addCriterion("employee_position_name >=", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameLessThan(String value) {
            addCriterion("employee_position_name <", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameLessThanOrEqualTo(String value) {
            addCriterion("employee_position_name <=", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameLike(String value) {
            addCriterion("employee_position_name like", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameNotLike(String value) {
            addCriterion("employee_position_name not like", value, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameIn(List<String> values) {
            addCriterion("employee_position_name in", values, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameNotIn(List<String> values) {
            addCriterion("employee_position_name not in", values, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameBetween(String value1, String value2) {
            addCriterion("employee_position_name between", value1, value2, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNameNotBetween(String value1, String value2) {
            addCriterion("employee_position_name not between", value1, value2, "employeePositionName");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneIsNull() {
            addCriterion("employee_cellphone is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneIsNotNull() {
            addCriterion("employee_cellphone is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneEqualTo(String value) {
            addCriterion("employee_cellphone =", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneNotEqualTo(String value) {
            addCriterion("employee_cellphone <>", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneGreaterThan(String value) {
            addCriterion("employee_cellphone >", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneGreaterThanOrEqualTo(String value) {
            addCriterion("employee_cellphone >=", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneLessThan(String value) {
            addCriterion("employee_cellphone <", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneLessThanOrEqualTo(String value) {
            addCriterion("employee_cellphone <=", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneLike(String value) {
            addCriterion("employee_cellphone like", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneNotLike(String value) {
            addCriterion("employee_cellphone not like", value, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneIn(List<String> values) {
            addCriterion("employee_cellphone in", values, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneNotIn(List<String> values) {
            addCriterion("employee_cellphone not in", values, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneBetween(String value1, String value2) {
            addCriterion("employee_cellphone between", value1, value2, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeCellphoneNotBetween(String value1, String value2) {
            addCriterion("employee_cellphone not between", value1, value2, "employeeCellphone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneIsNull() {
            addCriterion("employee_telephone is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneIsNotNull() {
            addCriterion("employee_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneEqualTo(String value) {
            addCriterion("employee_telephone =", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotEqualTo(String value) {
            addCriterion("employee_telephone <>", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneGreaterThan(String value) {
            addCriterion("employee_telephone >", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("employee_telephone >=", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneLessThan(String value) {
            addCriterion("employee_telephone <", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneLessThanOrEqualTo(String value) {
            addCriterion("employee_telephone <=", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneLike(String value) {
            addCriterion("employee_telephone like", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotLike(String value) {
            addCriterion("employee_telephone not like", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneIn(List<String> values) {
            addCriterion("employee_telephone in", values, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotIn(List<String> values) {
            addCriterion("employee_telephone not in", values, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneBetween(String value1, String value2) {
            addCriterion("employee_telephone between", value1, value2, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotBetween(String value1, String value2) {
            addCriterion("employee_telephone not between", value1, value2, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusIsNull() {
            addCriterion("employee_status is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusIsNotNull() {
            addCriterion("employee_status is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusEqualTo(Integer value) {
            addCriterion("employee_status =", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotEqualTo(Integer value) {
            addCriterion("employee_status <>", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusGreaterThan(Integer value) {
            addCriterion("employee_status >", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_status >=", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusLessThan(Integer value) {
            addCriterion("employee_status <", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("employee_status <=", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusIn(List<Integer> values) {
            addCriterion("employee_status in", values, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotIn(List<Integer> values) {
            addCriterion("employee_status not in", values, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusBetween(Integer value1, Integer value2) {
            addCriterion("employee_status between", value1, value2, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_status not between", value1, value2, "employeeStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}