package com.hihihigh.crm.model.autogenerator;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table name_authority
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class NameAuthority {
    /**
     * Database Column Remarks:
     *   authority表的type
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_authority.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   authority名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_authority.na_name
     *
     * @mbggenerated
     */
    private String naName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_authority.na_remark
     *
     * @mbggenerated
     */
    private String naRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_authority.id
     *
     * @return the value of name_authority.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_authority.id
     *
     * @param id the value for name_authority.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_authority.na_name
     *
     * @return the value of name_authority.na_name
     *
     * @mbggenerated
     */
    public String getNaName() {
        return naName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_authority.na_name
     *
     * @param naName the value for name_authority.na_name
     *
     * @mbggenerated
     */
    public void setNaName(String naName) {
        this.naName = naName == null ? null : naName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_authority.na_remark
     *
     * @return the value of name_authority.na_remark
     *
     * @mbggenerated
     */
    public String getNaRemark() {
        return naRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_authority.na_remark
     *
     * @param naRemark the value for name_authority.na_remark
     *
     * @mbggenerated
     */
    public void setNaRemark(String naRemark) {
        this.naRemark = naRemark == null ? null : naRemark.trim();
    }
}