package com.hihihigh.crm.model.autogenerator;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table position
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Position {
    /**
     * Database Column Remarks:
     *   职位表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   职位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_name
     *
     * @mbggenerated
     */
    private String positionName;

    /**
     * Database Column Remarks:
     *   部门表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_department_id
     *
     * @mbggenerated
     */
    private Integer positionDepartmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.id
     *
     * @return the value of position.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.id
     *
     * @param id the value for position.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_name
     *
     * @return the value of position.position_name
     *
     * @mbggenerated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_name
     *
     * @param positionName the value for position.position_name
     *
     * @mbggenerated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_department_id
     *
     * @return the value of position.position_department_id
     *
     * @mbggenerated
     */
    public Integer getPositionDepartmentId() {
        return positionDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_department_id
     *
     * @param positionDepartmentId the value for position.position_department_id
     *
     * @mbggenerated
     */
    public void setPositionDepartmentId(Integer positionDepartmentId) {
        this.positionDepartmentId = positionDepartmentId;
    }

	public Position() {
		super();
	}

	public Position(String positionName, Integer positionDepartmentId) {
		super();
		this.positionName = positionName;
		this.positionDepartmentId = positionDepartmentId;
	}
}