package com.hihihigh.crm.model.autogenerator;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table status_custmer
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class StatusCustmer {
    /**
     * Database Column Remarks:
     *   客户状态表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_custmer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   客户状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_custmer.status_name
     *
     * @mbggenerated
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_custmer.id
     *
     * @return the value of status_custmer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_custmer.id
     *
     * @param id the value for status_custmer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_custmer.status_name
     *
     * @return the value of status_custmer.status_name
     *
     * @mbggenerated
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_custmer.status_name
     *
     * @param statusName the value for status_custmer.status_name
     *
     * @mbggenerated
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}